---
- debug: var=cloud_instance_item.user_data_file

- name: Find the cloud user data file
  set_fact:
    cloud_user_data: "{{ lookup('file', item) }}"
  with_first_found:
    - files:
        - "{{ cloud_instance_item.user_data_file }}"
        - "{{ cloud_instance_item.user_data_file }}.user_data"
      paths:
        - "{{ playbook_dir }}"
        - "{{ playbook_dir }}/user-data"
        - "{{ playbook_dir }}/files"
        - "{{ inventory_dir }}"
